config/routes.rb
Rails.application.routes.draw do
  
  get 'users/show'

  devise_for :users
  root             'static_pages#home'
  get 'blog'    => 'static_pages#blog'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  
  match 'users/:id' => 'users#show', via: :get
  
  resources :users
  resources :snippets,  only: [:create, :destroy]

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :delay, presence: true
  validates :content, presence: true, length: { maximum: 5000 }
  validates :title, presence: true, length: { maximum: 50 }
  validate :picture_size
  
  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :snippets, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def logged_in_user
    unless user_signed_in?
      flash[:danger] = "Please log in."
      redirect_to new_user_session_path
    end
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]

  def create
    @snippet = current_user.snippets.build(snippet_params)
    if @snippet.save
      flash[:success] = "Snippet added to your time capsule!"
      redirect_to current_user
    else
      render 'static_pages/home'
    end
  end

  def destroy
  end

  private

    def snippet_params
      params.require(:snippet).permit(:title, :content, :picture, :delay)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @snippet = current_user.snippets.build if user_signed_in?
  end

  def about
  end

  def contact
  end
  
  def blog
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @snippets = @user.snippets.paginate(page: params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Time Capsule"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Where the past is cherished.
    </small>
    <nav>
      <ul>
        <li><%= link_to "About",   about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Blog", blog_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top navbar-inner">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a><%= link_to "Time Capsule", root_path, id: "logo" %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="container">
        <ul class="nav navbar-nav navbar-right">
          
          <% if !user_signed_in? %>
            <li><%= link_to "HOME", root_path, id: "nav_element" %></li>
            <li><%= link_to "ABOUT", about_path, id: "nav_element" %></li>
            <li><%= link_to "SIGN UP", new_user_registration_path, id: "nav_element" %></li>
            <li><%= link_to "LOGIN", new_user_session_path, id: "nav_element" %></li>
          <% else %>
            <li><%= link_to "NEW SNIPPET", root_path, id: "nav_element" %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle nav_element" data-toggle="dropdown">
                <%= current_user.email %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Profile', user_path(current_user.id), id: "nav_element" %></li>
                <li><%= link_to 'Edit profile', edit_user_registration_path, id: "nav_element" %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, id: "nav_element" %>
                </li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= image_tag "bg#{rand(1..4)}.jpg", class: 'bg' %>
	
	  <div id="page-wrap">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_snippet_form.html.erb
<h2>Add a snippet</h2>

<%= form_for(@snippet, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :title, placeholder: "Add a title..." %>
  </div>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new snippet..." %>
  </div>
  
  <div class="field">
    <%= f.select :delay, [['3 minutes', Time.now + 3.minutes], ['1 week', Time.now + 1.week], ['1 month', Time.now + 1.month], ['1 year', Time.now + 1.year], ['5 years', Time.now + 5.years], ['10 years', Time.now + 10.years]] %>
  </div>
  
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
  <%= f.submit "Add to capsule", class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  $('#snippet_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/snippets/_snippet.html.erb
<li id="snippet-<%= snippet.id %>">
  <span class="user" style="font-size:20px;"><%= snippet.title %></span>
  <% if !((snippet.delay) > Time.now) %>
    <span class="content"><%= snippet.content %></span>
    <%= image_tag snippet.picture.url if snippet.picture? %>
    <span class="timestamp">
      Written <%= time_ago_in_words(snippet.created_at) %> ago.
    </span>
  <% else %>
    <span class="content">This snippet is not available yet. Come back later to see it!</span>
    <span class="timestamp">
      You have to wait <%= distance_of_time_in_words(snippet.delay, Time.now) %>.
    </span>
  <% end %>
</li>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h2 style="font-size: 40px" class="home">About</h2>

<p class="field">
Time Capsule is specially designed to store all of your cherished memories. Be it a quote, photo, anecdote, or life goal. Each memory can be tailored to specify the exact time you wish to view it in the future.
</p>
<p class="field">
Time Capsule is the first app created by student developer <%= link_to "David Newell", contact_path %> and he is always welcome to hear input of users on the app, be it feature suggestions for the app, constructive criticism or even a thoughtful note.
</p>

app/views/static_pages/blog.html.erb
<% provide(:title, 'Blog') %>
<h1>Time Capsule Blog</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, "Team") %>

<h2 style="font-size: 40px" class="home">The Team (of one)</h2>
	<div>
	    <%= link_to image_tag('david.jpeg'), 'index', class:"img-circle" %>
	</div>
	<p class="field">
		By day David studies Electronic and Computer Engineering at his local university in Galway. By night, he also studies.
		 During his limited free time he chooses to do some extra study...Or go to the cinema with his m8's and play his PlayStation 
		 (Challenge him to a game of FIFA15). He's lives at home like any good mama's boy, with his mamaBear, papaBear and sisterCub, Lisa.
		 He's an avid lover of all things tech, and you are currently visiting his first ever Rails app; tell him you've used it(even if you 
		 haven't).
	</p>
	<p>
		<strong style="color:white;">Email: </strong><a href="mailto:youremailaddress" class="nav_element">d.newell4@nuigalway.ie</a><br>
		<strong style="color:white;">Twitter: </strong><a href="https://twitter.com/davidnewell95">@DavidNewell95</a>
	</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<% if user_signed_in? %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <section class="snippet_form">
        <%= flash[:success] %>
        <%= render 'shared/snippet_form' %>
      </section>
    </div>
  </div>
<% else %>
		<h2 style="font-size:60px" class="home">Time Capsule</h2>
		<hr class="small">
    <h2 class="home">We cherish your past.</h2>
    <%= link_to "Sign up", new_user_registration_path, id:"signup_btn" %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.email) %>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
  	<h2 style="font-size:40px" class="home">My Snippets</h2>
    <% if @user.snippets.any? %>
      <% @snippets.each do |snippet| %>
        <ol class="snippets">
          <%= render snippet %>
        </ol>
      <% end %>
      <%= will_paginate @snippets %>
    <% end %>
  </div>
</div>